version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: carteira_digital_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_segura_123
      POSTGRES_DB: carteira_digital
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: